version: '3.5'

services:

  coopdb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mysecret
    image: mongo:4-bionic
    volumes:
      - coopdata:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - coopnet

  coopapp:
    environment:
      - NODE_ENV=development
      - PORTHTTP=3000
      - PORTWS=3001
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - coopdb
    command: /bin/sh -c 'npm i && npm run debug'
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
      - "3001:3001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health && echo 'OK'"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 3
    restart: unless-stopped
    networks:
      coopnet:

  coopproxy:
    image: nginx:alpine
    depends_on:
      - coopapp
    ports:
      - "80:80"
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health && echo 'OK'"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 3
    networks:
      coopnet:

volumes:
  coopdata:

networks:
  coopnet:
